// Sentinel actorId for tenant_events rows generated by the cron (no Better Auth user).
// tenant_events.actorId is text NOT NULL with no FK — "system" matches the sentinel
// convention already used elsewhere in the codebase (see quota-notify.ts `who: "system"`).
export const CRON_SYSTEM_ACTOR_ID = "system";
